name: jaxneurorl
channels:
  - conda-forge
dependencies:
  - pip:
    - wandb
    - "xminigrid==0.6.0"
    - ipdb
    - tqdm
    - rlax
    - mctx==0.0.5
    - "ray[tune]"
    - jupyterlab
    - ipywidgets