# rollouts
"NUM_ENVS": 2
"TRAINING_INTERVAL": 100
"TOTAL_TIMESTEPS": 5_000
# eval-specific
"EVAL_EPISODES": 2
"EVAL_STEPS": 150


# batches
"BUFFER_SIZE": 1_000
"LEARNING_STARTS": 100
"BUFFER_BATCH_SIZE": 1
"SAMPLE_LENGTH": 40

# logging
"LEARNER_LOG_PERIOD": 1
"GRADIENT_LOG_PERIOD": 1
"LEARNER_EXTRA_LOG_PERIOD": 1
"EVAL_LOG_PERIOD": 1
"DEBUG": True