# rollouts
"NUM_ENVS": 2
"TRAINING_INTERVAL": 1
"TOTAL_TIMESTEPS": 50
"NUM_EXTRA_REPLAY": 4
# eval-specific
"EVAL_EPISODES": 1
"EVAL_STEPS": 10


# batches
"BUFFER_SIZE": 100
"LEARNING_STARTS": 0
"TOTAL_BATCH_SIZE": 6
"BUFFER_BATCH_SIZE": 2
"SAMPLE_LENGTH": null
"TOTAL_EXTRA_BATCH_SIZE": null
"EXTRA_BATCH_SIZE": 3
"EXTRA_SAMPLE_LENGTH": null

# logging
"LEARNER_LOG_PERIOD": 1
"GRADIENT_LOG_PERIOD": 1
"LEARNER_EXTRA_LOG_PERIOD": 1
"EVAL_LOG_PERIOD": 1
"MAX_EPISODE_LOG_LEN": 2
"DEBUG": True
"OBSERVER_PERIOD": 10
"OBSERVER_EPISODES": 1


# 
"NUM_SIMULATIONS": 2
"SIMULATION_LENGTH": 3


# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 16
"IMAGE_HIDDEN": 16
"AGENT_RNN_DIM": 16
"GRID_HIDDEN": 16
"NUM_BINS": 11
"NUM_EMBED_LAYERS": 0
"NUM_GRID_LAYERS": 1
"NUM_ENCODER_LAYERS": 1

"ENV_KWARGS":
  time_limit: 4
