# rollouts
"NUM_ENVS": 2
"NUM_STEPS": 100
"TOTAL_TIMESTEPS": 5_000
# eval-specific
"EVAL_EPISODES": 1
"EVAL_STEPS": 100


# batches
"BUFFER_SIZE": 1_000
"LEARNING_STARTS": 100
"BUFFER_BATCH_SIZE": 3
"SAMPLE_LENGTH": 5

# logging
"LEARNER_LOG_PERIOD": 1