# rollouts
"NUM_ENVS": 2
"TRAINING_INTERVAL": 100
"TOTAL_TIMESTEPS": 5_000
# eval-specific
"EVAL_EPISODES": 1
"EVAL_STEPS": 10


# batches
"BUFFER_SIZE": 1_000
"LEARNING_STARTS": 0
"BUFFER_BATCH_SIZE": 1
"SAMPLE_LENGTH": 4

# logging
"LEARNER_LOG_PERIOD": 1
"GRADIENT_LOG_PERIOD": 1
"LEARNER_EXTRA_LOG_PERIOD": 1
"EVAL_LOG_PERIOD": 1
"MAX_EPISODE_LOG_LEN": 2
"DEBUG": True


# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 16
"IMAGE_HIDDEN": 16
"AGENT_RNN_DIM": 16
"NUM_BINS": 11
