# rollouts
"NUM_ENVS": 2
"TRAINING_INTERVAL": 1
"TOTAL_TIMESTEPS": 5_000
# eval-specific
"EVAL_EPISODES": 1
"EVAL_STEPS": 10


# batches
"BUFFER_SIZE": 100
"LEARNING_STARTS": 0
"BUFFER_BATCH_SIZE": 1
"SAMPLE_LENGTH": 4

# logging
"LEARNER_LOG_PERIOD": 1
"GRADIENT_LOG_PERIOD": 1
"LEARNER_EXTRA_LOG_PERIOD": 1
"EVAL_LOG_PERIOD": 1
"MAX_EPISODE_LOG_LEN": 2
"DEBUG": True
"OBSERVER_PERIOD": 10
"OBSERVER_EPISODES": 1


# 
"NUM_SIMULATIONS": 2
"SIMULATION_LENGTH": 1


# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 16
"IMAGE_HIDDEN": 16
"AGENT_RNN_DIM": 16
"NUM_BINS": 11

"ENV_KWARGS":
  time_limit: 4
