"PROJECT": "jax-neurorl-baselines"


# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

"ALG": 'qlearning'

# RUN PARAMS
"NUM_ENVS": 10
"EVAL_STEPS": 100
"EVAL_EPISODES": 100
"TOTAL_TIMESTEPS": 1e7
"VERBOSE": FALSE
"WANDB_ONLINE_REPORT": TRUE
"ACTOR_LOG_PERIOD": 10_000  # every this number of steps
"LEARNER_LOG_PERIOD": 50_000  # every this number of learner updates

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 128
"NUM_BINS": 101

# MCTS PARAMS
#"MAX_SIM_DEPTH": 100
"NUM_SIMULATIONS": 4
"GUMBEL_SCALE": 1.0

# ALGO PARAMS
"BUFFER_SIZE": 10_000
"BUFFER_BATCH_SIZE": 32
"SAMPLE_LENGTH": 20
"LEARNING_STARTS": 10_000
"TRAINING_INTERVAL": 10

"MAX_GRAD_NORM": 80
"TARGET_UPDATE_INTERVAL": 1_000
"LR": 0.001
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001
"GAMMA": 0.99

hydra/output_subdir: null
hydra/hydra_logging: disabled
hydra/job_logging: disabled


defaults:
- _self_
- user: wilka.yaml
- debug: default.yaml
- env: cartpole.yaml
