# WANDB PARAMS

"ENV_NAME": "CartPole-v1"

# RUN PARAMS
"NUM_ENVS": 32
"NUM_STEPS": 10
"EVAL_EPISODES": 100

# RUN PARAMS
"TOTAL_TIMESTEPS": 1e6
"EPSILON_ANNEAL_TIME": 5e5

# ALGO PARAMS
"LEARNING_STARTS": 10_000
"BUFFER_SIZE": 50_000
"BUFFER_BATCH_SIZE": 32
"TARGET_UPDATE_INTERVAL": 1000

"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
