# WANDB PARAMS

"ENV_NAME": "CartPole-v1"

# RUN PARAMS
"EVAL_EPISODES": 100

# RUN PARAMS
"TOTAL_TIMESTEPS": 1e6

# ALGO PARAMS
"LEARNING_STARTS": 10_000

"EPSILON_ANNEAL_TIME": 5e5
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.05
