"ALG": 'qlearning'

# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

# loggging
"MAX_EPISODE_LOG_LEN": 40


# RUN PARAMS
"TOTAL_TIMESTEPS": 1e7
"NUM_ENVS": 32
"EVAL_STEPS": 100
"EVAL_EPISODES": 100
"LEARNER_LOG_PERIOD": 500
"LEARNER_EXTRA_LOG_PERIOD": 0
"EVAL_LOG_PERIOD": 1_000
"GRADIENT_LOG_PERIOD": 5_000

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 32
"IMAGE_HIDDEN": 256
"ENCODER_INIT": 'word_init'
"RNN_CELL_TYPE": 'LSTMCell'
"AGENT_RNN_DIM": 256
"NUM_BINS": 101

# ALGO PARAMS
"BUFFER_SIZE": 50_000
"BUFFER_BATCH_SIZE": 32
"SAMPLE_LENGTH": 40
"LEARNING_STARTS": 10_000
"TRAINING_INTERVAL": 10


"MAX_GRAD_NORM": 80
"TARGET_UPDATE_INTERVAL": 1_000
"LR": 0.001
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001
"GAMMA": 0.99


hydra/output_subdir: null
hydra/hydra_logging: disabled
hydra/job_logging: disabled


defaults:
- _self_
- user: wilka.yaml
- debug: short.yaml
- env: keyroom.yaml
