# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

"ALG": 'qlearning'

# RUN PARAMS
"NUM_ENVS": 32
"NUM_STEPS": 256
"EVAL_STEPS": 100
"EVAL_EPISODES": 100
"TOTAL_TIMESTEPS": int(10e7)
"VERBOSE": FALSE
"WANDB_ONLINE_REPORT": TRUE
"ACTOR_LOG_PERIOD": 10_000  # every this number of steps
"LEARNER_LOG_PERIOD": 50_000  # every this number of learner updates

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 256
"AGENT_INIT_SCALE": 2.

# ALGO PARAMS
"BUFFER_SIZE": 50_000
"BUFFER_BATCH_SIZE": 32
"SAMPLE_LENGTH": 20
"LEARNING_STARTS": 10_000
"TRAINING_INTERVAL": 10

"EPSILON_START": 1.0
"EPSILON_FINISH": 0.1
"EPSILON_ANNEAL_TIME": 1e6
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 2000
"LR": 0.005
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001

"GAMMA": 0.99

hydra/output_subdir: null
hydra/hydra_logging: disabled
hydra/job_logging: disabled


defaults:
- _self_
- user: wilka.yaml
- debug: short.yaml
- env: keyroom.yaml
