"ALG": 'qlearning'

# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

# logggin
"MAX_EPISODE_LOG_LEN": 40


# RUN PARAMS
"NUM_ENVS": 32
"EVAL_STEPS": 100
"EVAL_EPISODES": 100
"VERBOSE": FALSE
"WANDB_ONLINE_REPORT": TRUE
"ACTOR_LOG_PERIOD": 10_000
"LEARNER_LOG_PERIOD": 500
"GRADIENT_LOG_PERIOD": 500

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 32
"IMAGE_HIDDEN": 256
"RNN_CELL_TYPE": 'LSTMCell'
"AGENT_RNN_DIM": 256

# ALGO PARAMS
"BUFFER_SIZE": 50_000
"BUFFER_BATCH_SIZE": 32
"SAMPLE_LENGTH": 20
"LEARNING_STARTS": 10_000
"TRAINING_INTERVAL": 10

"TOTAL_TIMESTEPS": 1e7
"EPSILON_START": 1.0
"EPSILON_FINISH": 0.1
"EPSILON_ANNEAL_TIME": 5e5
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 1_000
"LR": 0.001
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001

"GAMMA": 0.99

hydra/output_subdir: null
hydra/hydra_logging: disabled
hydra/job_logging: disabled


defaults:
- _self_
- user: wilka.yaml
- debug: short.yaml
- env: keyroom.yaml
