# EXPERIMENT PARAMS
"NUM_SEEDS": 1
"SEED": 1

"ALG": 'dyna'

# RUN PARAMS
"NUM_ENVS": 32
"EVAL_STEPS": 100
"EVAL_EPISODES": 100
"TOTAL_TIMESTEPS": 1e7
"LEARNER_LOG_PERIOD": 500
"LEARNER_EXTRA_LOG_PERIOD": 5_000
"EVAL_LOG_PERIOD": 5_000
"GRADIENT_LOG_PERIOD": 5_000

# NEURAL NET PARAMS
"AGENT_HIDDEN_DIM": 128
"AGENT_INIT_SCALE": 2.
"AGENT_USE_BIAS": False

# ALGO PARAMS
"BUFFER_SIZE": 10_000
"BUFFER_BATCH_SIZE": 32
"SAMPLE_LENGTH": 20
"LEARNING_STARTS": 10_000
"TRAINING_INTERVAL": 10

"EPSILON_START": 1.0
"EPSILON_FINISH": 0.1
"EPSILON_ANNEAL_TIME": 1e6
"MAX_GRAD_NORM": 10
"TARGET_UPDATE_INTERVAL": 2000
"LR": 0.005
"LR_LINEAR_DECAY": FALSE
"EPS_ADAM": 0.00001
"GAMMA": 0.99
"FIXED_EPSILON": 2